apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 1m
  path: ./infrastructure/stage
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-config
  timeout: 2m
  wait: true