apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  chart:
    spec:
      chart: velero
      version: '10.1.0'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  install:
    crds: "Create" 
  upgrade:
    crds: "Create"  
  values:
    image:
      repository: velero/velero
      tag: v1.16.2
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:latest
        volumeMounts:
          - mountPath: /target
            name: plugins
    upgradeCRDs: true
    configuration:
      backupStorageLocation:
        - name: default
          provider: aws
          bucket: my-velero-backups-12345
          config:
            region: us-east-1
      uploaderType: restic
      logLevel: warning
      extraEnvVars:
      - name: TZ
        value: "Africa/Accra"
      defaultVolumesToFsBackup: true
    credentials:
      existingSecret: cloud-credentials
    backupsEnabled: true
    snapshotsEnabled: false
    deployNodeAgent: true
    nodeAgent:
      tolerations:
        - key: k8s.pascaliske.dev/location
          operator: Equal
          value: public
          effect: NoSchedule
    schedules:
      weekly:
        schedule: '0 3 * * 0'
        template:
          includedNamespaces:
            - '*'
  interval: 10m
