---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress-app
spec:
  chart:
    spec:
      chart: wordpress
      version: 0.14.2
      sourceRef:
        kind: HelmRepository
        name: groundhog2k
        namespace: flux-system
  interval: 15m
  install:
    createNamespace: false
  values:
    mariadb:
      enabled: false
    externalDatabase:
      host: "mariadb.databases.svc.cluster.local"
      port: 3306
      database: "wordpress"
      username: "admin"
      password: "Admin12345"
    settings:
      wordpress:
        admin:
          existingSecret: "mariadb-secret1"
          userKey: "wordpress-admin-user"
          passwordKey: "wordpress-admin-password"
          emailKey: "wordpress-admin-email"
        tablePrefix: "wp_"
    service:
      type: LoadBalancer
    storage:
      className: longhorn
      accessModes:
        - ReadWriteOnce
      size: 10Gi
    
    # Optional: Configure ingress instead of LoadBalancer
    # ingress:
    #   enabled: true
    #   className: "nginx"  # or your ingress class
    #   hosts:
    #     - host: wordpress.blkh.dev
    #       paths:
    #         - path: /
    #           pathType: Prefix
    #   tls:
    #     - secretName: wordpress-tls
    #       hosts:
    #         - wordpress.blkh.dev
