---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress-app
spec:
  chart:
    spec:
      chart: wordpress
      version: 0.14.2
      sourceRef:
        kind: HelmRepository
        name: groundhog2k
        namespace: flux-system
      interval: 5m
  interval: 15m
  valuesFrom:
    - kind: Secret
      name: mariadb-secret1
      valuesKey: rootPassword
      targetPath: mariadb.auth.rootPassword
    - kind: Secret
      name: mariadb-secret1
      valuesKey: username
      targetPath: mariadb.auth.username
    - kind: Secret
      name: mariadb-secret1
      valuesKey: password
      targetPath: mariadb.auth.password
    - kind: Secret
      name: mariadb-secret1
      valuesKey: database
      targetPath: mariadb.auth.database
  values:
    mariadb:
      enabled: true
      persistence:
        enabled: true
        size: 10Gi
        storageClass: gp2
    service:
      type: LoadBalancer
    storage:
      className: gp2
      accessModes:
        - ReadWriteOnce
      size: 10Gi
