---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb
  namespace: wordpress-app
spec:
  chart:
    spec:
      chart: mariadb
      version: 0.9.1
      sourceRef:
        kind: HelmRepository
        name: groundhog2k
        namespace: flux-system
  interval: 5m
  valuesFrom:
    - kind: Secret
      name: mariadb-secret
      valuesKey: mariadb-root-password
      targetPath: auth.rootPassword
    - kind: Secret
      name: mariadb-secret
      valuesKey: mariadb-username
      targetPath: auth.username
    - kind: Secret
      name: mariadb-secret
      valuesKey: mariadb-password
      targetPath: auth.password
    - kind: Secret
      name: mariadb-secret
      valuesKey: mariadb-database
      targetPath: auth.database
  values:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: gp2
    service:
      type: ClusterIP

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress-app
spec:
  chart:
    spec:
      chart: wordpress
      version: 0.14.2
      sourceRef:
        kind: HelmRepository
        name: groundhog2k
        namespace: flux-system
  interval: 5m
  valuesFrom:
    - kind: Secret
      name: mariadb-secret
      valuesKey: mariadb-username
      targetPath: externalDatabase.user
    - kind: Secret
      name: mariadb-secret
      valuesKey: mariadb-password
      targetPath: externalDatabase.password
    - kind: Secret
      name: mariadb-secret
      valuesKey: mariadb-database
      targetPath: externalDatabase.name
  values:
    externalDatabase:
      host: mariadb.wordpress-app.svc.cluster.local
    service:
      type: LoadBalancer
    storage:
      className: gp2
      accessModes:
        - ReadWriteOnce
      size: 10Gi
