---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress-app
spec:
  chart:
    spec:
      chart: wordpress
      version: 0.14.2
      sourceRef:
        kind: HelmRepository
        name: groundhog2k
        namespace: flux-system
      interval: 5m
  interval: 15m
  values:
    mariadb:
      enabled: true
      auth:
        rootPassword: "rootadmin12345"
        username: "admin"
        password: "Admin12345"
        database: "wordpress"
      persistence:
        enabled: true
        size: 10Gi
        storageClass: gp2
    service:
      type: LoadBalancer
    storage:
      className: gp2
      accessModes:
        - ReadWriteOnce
      size: 10Gi
