---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-0-nfs
  namespace: wordpress
spec:
  storageClassName: wordpress
  capacity:
    storage: 1Mi # Size does not matter ...twss
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.20.0.1
    path: /volume1/Data/wordpress/wordpress-0

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-0-nfs
  namespace: wordpress
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: wordpress
  resources:
    requests:
      storage: 1Mi # Size does not matter ...twss