---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/monitoring.coreos.com/alertmanagerconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  route:
    groupBy:
      - alertname
      - job
    groupWait: 1m
    groupInterval: 10m
    repeatInterval: 12h
    receiver: pushover
    routes:
      - receiver: "null"
        matchers:
          - name: alertname
            value: InfoInhibitor
            matchType: "="
      - receiver: heartbeat
        groupWait: 0s
        groupInterval: 5m
        repeatInterval: 5m
        matchers:
          - name: alertname
            value: Watchdog
            matchType: "="
      - receiver: pushover
        matchers:
          - name: severity
            value: critical
            matchType: "="
  inhibitRules:
    - sourceMatch:
        - name: severity
          value: critical
          matchType: "="
      targetMatch:
        - name: severity
          value: warning
          matchType: "="
      equal:
        - alertname
        - namespace
  receivers:
    - name: "null"
    - name: heartbeat
      webhookConfigs:
        - urlSecret:
            name: alertmanager-secret
            key: ALERTMANAGER_HEARTBEAT_URL
    - name: pushover
      pushoverConfigs:
        - sendResolved: true
          title: >-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}]
            {{ .CommonLabels.alertname }}
          message: |-
            {{- range .Alerts }}
            {{- if ne .Annotations.description "" }}
              {{ .Annotations.description }}
            {{- else if ne .Annotations.summary "" }}
              {{ .Annotations.summary }}
            {{- else if ne .Annotations.message "" }}
              {{ .Annotations.message }}
            {{- else }}
              Alert description not available
            {{- end }}
            {{- if gt (len .Labels.SortedPairs) 0 }}
              <small>
              {{- range .Labels.SortedPairs }}
                <b>{{ .Name }}:</b> {{ .Value }}
              {{- end }}
              </small>
            {{- end }}
            {{- end }}
          html: true
          sound: gamelan
          priority: "{{ if eq .Status \"firing\" }}1{{ else }}0{{ end }}"
          ttl: 86400s
          token:
            name: alertmanager-secret
            key: ALERTMANAGER_PUSHOVER_TOKEN
          userKey:
            name: alertmanager-secret
            key: PUSHOVER_USER_KEY
          url: https://alertmanager.example.com
          urlTitle: View in Alertmanager