# infrastructure/stage/scrapeconfigs.yaml
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: airgradient
  namespace: monitoring  
spec:
  staticConfigs:
    - targets: ["airgradient.outsideour.casa:9926"]
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: airgradient
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: node-exporter
  namespace: monitoring  
spec:
  staticConfigs:
    - targets: ["fran.outsideour.casa:9100"]
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: node-exporter
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: smartctl-exporter
  namespace: monitoring  
spec:
  staticConfigs:
    - targets: ["fran.outsideour.casa:9633"]
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: smartctl-exporter